POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OGM3OTVlMWJlMzIxMjg2YjJlZDZlZTEiLCJpYXQiOjE3NTc5OTc1Mjh9.yKYl_kKaglu2dktMjZaNtpuBxckQcM9JFOJmSaC3o98

{
    "content": "Authorized Note",
    "important": true
}